

CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	CLIENT_ID VARCHAR(50) UNIQUE,
	CUSTOMER_NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	COMPANY_NAME VARCHAR(100)
);

drop table orders;

CREATE TABLE ORDERS (
	ORDER_ID SERIAL PRIMARY KEY,
	CLIENT_ID VARCHAR(50),
	EQUIPMENT_ID INTEGER,
	ORDER_STATUS VARCHAR(50),
	DELIVERY_DATE DATE,
	TRACKING_NUMBER VARCHAR(100)
);

CREATE TABLE EQUIPMENT (
	EQUIPMENT_ID SERIAL PRIMARY KEY,
	EQUIPMENT_NAME VARCHAR(100),
	MODEL_NUMBER VARCHAR(100),
	SERIAL_NUMBER VARCHAR(100),
	INSTALLATION_DATE DATE
);

CREATE TABLE WARRANTY (
	WARRANTY_ID SERIAL PRIMARY KEY,
	EQUIPMENT_ID INTEGER,
	CLIENT_ID VARCHAR(50),
	START_DATE DATE,
	END_DATE DATE,
	AMC_STATUS VARCHAR(50)
);

CREATE TABLE COMPLAINTS (
	TICKET_ID SERIAL PRIMARY KEY,
	CLIENT_ID VARCHAR(50),
	ISSUE_DESCRIPTION TEXT,
	STATUS VARCHAR(50),
	CREATED_AT TIMESTAMP
);


CREATE TABLE INVOICES (
	INVOICE_ID SERIAL PRIMARY KEY,
	CLIENT_ID VARCHAR(50),
	AMOUNT NUMERIC,
	INVOICE_DATE DATE,
	INVOICE_LINK TEXT
);

CREATE TABLE user_sessions (
    session_id VARCHAR(255) PRIMARY KEY,
    client_id VARCHAR(100),
    email VARCHAR(255),
    authenticated BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
